<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1672800179678' stop='1672800202762'>
    <name>Realizar Login no App</name>
    <title>Realizar Login no App</title>
    <test-cases>
        <test-case start='1672800179678' status='broken' stop='1672800202756'>
            <name>Deve realizar Login</name>
            <title>Deve realizar Login</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='device' value='ebac-qe 9.0-9'/>
            </parameters>
            <steps/>
            <attachments>
                <attachment title='Execution video' source='9bf0516c-6d2e-4389-a0c3-5dfddddab521-attachment.mp4' type='video/mp4' size='167'/>
            </attachments>
            <failure>
                <message>element ("//android.view.View[@content-desc="Lu Bolachas Olá, Fazer Login"]") still not existing after 20000ms</message>
                <stack-trace>Error: element ("//android.view.View[@content-desc="Lu Bolachas Olá, Fazer Login"]") still not existing after 20000ms
                    at E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\node_modules\webdriverio\build\commands\browser\waitUntil.js:66:23
                    at async Element.wrapCommandFn (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\node_modules\@wdio\utils\build\shim.js:137:29)
                    at async Element.elementErrorHandlerCallbackFn (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\node_modules\webdriverio\build\middlewares.js:24:32)
                    at async Element.wrapCommandFn (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\node_modules\@wdio\utils\build\shim.js:137:29)
                    at async Element.wrapCommandFn (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\node_modules\@wdio\utils\build\shim.js:137:29)
                    at async Element.elementErrorHandlerCallbackFn (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\node_modules\webdriverio\build\middlewares.js:24:32)
                    at async Element.wrapCommandFn (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\node_modules\@wdio\utils\build\shim.js:137:29)
                    at async HomeScreen.goToLogin (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\test\screens\home.screen.js:16:9)
                    at async Context.&lt;anonymous> (E:\Particular\Studies\Ebac_Local\LuBolachas\teste_app_flutter\test\specs\login.spec.js:11:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>